version: '3'

services:
  rag-app:
    build: .
    ports:
      - "8000:8000"  # FastAPI порт
      - "8501:8501"  # Streamlit порт
    volumes:
      - ./Research:/app/Research  # Монтирование папки документов
    environment:
      - OLLAMA_HOST=host.docker.internal  # Для Windows/Mac OS доступ к Ollama на хосте

    # Для корректной работы с хостом в Docker на Windows/Mac
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge 