version: '3.8'

services:
  # База данных MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: db
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123123"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  # Инициализация базы данных
  db_init:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: db_init
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:123123@db:3306/db
    volumes:
      - ./server:/app
    command: python init_db.py
    restart: "no"
    networks:
      - app_network

  # Бэкенд (FastAPI)
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_app
    restart: always
    depends_on:
      - db_init
      - ollama
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:123123@db:3306/db
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./server:/app
    command: >
      sh -c "python -m uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app_network

  # Фронтенд (Vue.js)
  frontend:
    build:
      context: ./vite-soft-ui-dashboard-main
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    ports:
      - "0.0.0.0:8080:80"
    depends_on:
      - backend
    networks:
      - app_network

  # Ollama для LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    restart: always
    ports:
      - "0.0.0.0:11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  ollama_data: 